name: Test async

on:
  workflow_dispatch:
  schedule:
    - cron: "35 14 * * 1-5"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python setup.py install
          python -m playwright install firefox
      - name: run test
        run: python example/example.py
